/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases/$slug'
import { Route as StatusSlugRouteImport } from './routes/status/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardTeamIdRouteRouteImport } from './routes/(dashboard)/$teamId/route'
import { Route as GuidesIntegrationsSlugRouteImport } from './routes/guides/integrations/$slug'
import { Route as dashboardTeamIdTeamRouteImport } from './routes/(dashboard)/$teamId/team'
import { Route as dashboardTeamIdSupportRouteImport } from './routes/(dashboard)/$teamId/support'
import { Route as dashboardTeamIdSettingsRouteImport } from './routes/(dashboard)/$teamId/settings'
import { Route as dashboardTeamIdNewTeamRouteImport } from './routes/(dashboard)/$teamId/new-team'
import { Route as dashboardTeamIdStatusPagesIndexRouteImport } from './routes/(dashboard)/$teamId/status-pages/index'
import { Route as dashboardTeamIdMonitorsIndexRouteImport } from './routes/(dashboard)/$teamId/monitors/index'
import { Route as dashboardTeamIdIntegrationsIndexRouteImport } from './routes/(dashboard)/$teamId/integrations/index'
import { Route as dashboardTeamIdIncidentsIndexRouteImport } from './routes/(dashboard)/$teamId/incidents/index'
import { Route as dashboardTeamIdHeartbeatsIndexRouteImport } from './routes/(dashboard)/$teamId/heartbeats/index'
import { Route as dashboardTeamIdStatusPagesNewRouteImport } from './routes/(dashboard)/$teamId/status-pages/new'
import { Route as dashboardTeamIdMonitorsNewRouteImport } from './routes/(dashboard)/$teamId/monitors/new'
import { Route as dashboardTeamIdIncidentsIncidentIdRouteImport } from './routes/(dashboard)/$teamId/incidents/$incidentId'
import { Route as dashboardTeamIdHeartbeatsNewRouteImport } from './routes/(dashboard)/$teamId/heartbeats/new'
import { Route as dashboardTeamIdStatusPagesPageIdIndexRouteImport } from './routes/(dashboard)/$teamId/status-pages/$pageId/index'
import { Route as dashboardTeamIdMonitorsMonitorIdIndexRouteImport } from './routes/(dashboard)/$teamId/monitors/$monitorId/index'
import { Route as dashboardTeamIdHeartbeatsHeartbeatIdIndexRouteImport } from './routes/(dashboard)/$teamId/heartbeats/$heartbeatId/index'
import { Route as dashboardTeamIdStatusPagesPageIdEditRouteImport } from './routes/(dashboard)/$teamId/status-pages/$pageId/edit'
import { Route as dashboardTeamIdMonitorsMonitorIdMaintenanceRouteImport } from './routes/(dashboard)/$teamId/monitors/$monitorId/maintenance'
import { Route as dashboardTeamIdMonitorsMonitorIdEditRouteImport } from './routes/(dashboard)/$teamId/monitors/$monitorId/edit'
import { Route as dashboardTeamIdHeartbeatsHeartbeatIdEditRouteImport } from './routes/(dashboard)/$teamId/heartbeats/$heartbeatId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTeamIdRouteRoute = dashboardTeamIdRouteRouteImport.update({
  id: '/(dashboard)/$teamId',
  path: '/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIntegrationsSlugRoute = GuidesIntegrationsSlugRouteImport.update({
  id: '/guides/integrations/$slug',
  path: '/guides/integrations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTeamIdTeamRoute = dashboardTeamIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => dashboardTeamIdRouteRoute,
} as any)
const dashboardTeamIdSupportRoute = dashboardTeamIdSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => dashboardTeamIdRouteRoute,
} as any)
const dashboardTeamIdSettingsRoute = dashboardTeamIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardTeamIdRouteRoute,
} as any)
const dashboardTeamIdNewTeamRoute = dashboardTeamIdNewTeamRouteImport.update({
  id: '/new-team',
  path: '/new-team',
  getParentRoute: () => dashboardTeamIdRouteRoute,
} as any)
const dashboardTeamIdStatusPagesIndexRoute =
  dashboardTeamIdStatusPagesIndexRouteImport.update({
    id: '/status-pages/',
    path: '/status-pages/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsIndexRoute =
  dashboardTeamIdMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdIntegrationsIndexRoute =
  dashboardTeamIdIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdIncidentsIndexRoute =
  dashboardTeamIdIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsIndexRoute =
  dashboardTeamIdHeartbeatsIndexRouteImport.update({
    id: '/heartbeats/',
    path: '/heartbeats/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdStatusPagesNewRoute =
  dashboardTeamIdStatusPagesNewRouteImport.update({
    id: '/status-pages/new',
    path: '/status-pages/new',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsNewRoute =
  dashboardTeamIdMonitorsNewRouteImport.update({
    id: '/monitors/new',
    path: '/monitors/new',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdIncidentsIncidentIdRoute =
  dashboardTeamIdIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsNewRoute =
  dashboardTeamIdHeartbeatsNewRouteImport.update({
    id: '/heartbeats/new',
    path: '/heartbeats/new',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdStatusPagesPageIdIndexRoute =
  dashboardTeamIdStatusPagesPageIdIndexRouteImport.update({
    id: '/status-pages/$pageId/',
    path: '/status-pages/$pageId/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsMonitorIdIndexRoute =
  dashboardTeamIdMonitorsMonitorIdIndexRouteImport.update({
    id: '/monitors/$monitorId/',
    path: '/monitors/$monitorId/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute =
  dashboardTeamIdHeartbeatsHeartbeatIdIndexRouteImport.update({
    id: '/heartbeats/$heartbeatId/',
    path: '/heartbeats/$heartbeatId/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdStatusPagesPageIdEditRoute =
  dashboardTeamIdStatusPagesPageIdEditRouteImport.update({
    id: '/status-pages/$pageId/edit',
    path: '/status-pages/$pageId/edit',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsMonitorIdMaintenanceRoute =
  dashboardTeamIdMonitorsMonitorIdMaintenanceRouteImport.update({
    id: '/monitors/$monitorId/maintenance',
    path: '/monitors/$monitorId/maintenance',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsMonitorIdEditRoute =
  dashboardTeamIdMonitorsMonitorIdEditRouteImport.update({
    id: '/monitors/$monitorId/edit',
    path: '/monitors/$monitorId/edit',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsHeartbeatIdEditRoute =
  dashboardTeamIdHeartbeatsHeartbeatIdEditRouteImport.update({
    id: '/heartbeats/$heartbeatId/edit',
    path: '/heartbeats/$heartbeatId/edit',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/status/$slug': typeof StatusSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/compare': typeof CompareIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/$teamId/new-team': typeof dashboardTeamIdNewTeamRoute
  '/$teamId/settings': typeof dashboardTeamIdSettingsRoute
  '/$teamId/support': typeof dashboardTeamIdSupportRoute
  '/$teamId/team': typeof dashboardTeamIdTeamRoute
  '/guides/integrations/$slug': typeof GuidesIntegrationsSlugRoute
  '/$teamId/heartbeats/new': typeof dashboardTeamIdHeartbeatsNewRoute
  '/$teamId/incidents/$incidentId': typeof dashboardTeamIdIncidentsIncidentIdRoute
  '/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/$teamId/status-pages/new': typeof dashboardTeamIdStatusPagesNewRoute
  '/$teamId/heartbeats': typeof dashboardTeamIdHeartbeatsIndexRoute
  '/$teamId/incidents': typeof dashboardTeamIdIncidentsIndexRoute
  '/$teamId/integrations': typeof dashboardTeamIdIntegrationsIndexRoute
  '/$teamId/monitors': typeof dashboardTeamIdMonitorsIndexRoute
  '/$teamId/status-pages': typeof dashboardTeamIdStatusPagesIndexRoute
  '/$teamId/heartbeats/$heartbeatId/edit': typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  '/$teamId/monitors/$monitorId/edit': typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  '/$teamId/monitors/$monitorId/maintenance': typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  '/$teamId/status-pages/$pageId/edit': typeof dashboardTeamIdStatusPagesPageIdEditRoute
  '/$teamId/heartbeats/$heartbeatId': typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  '/$teamId/monitors/$monitorId': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
  '/$teamId/status-pages/$pageId': typeof dashboardTeamIdStatusPagesPageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/status/$slug': typeof StatusSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/compare': typeof CompareIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/$teamId/new-team': typeof dashboardTeamIdNewTeamRoute
  '/$teamId/settings': typeof dashboardTeamIdSettingsRoute
  '/$teamId/support': typeof dashboardTeamIdSupportRoute
  '/$teamId/team': typeof dashboardTeamIdTeamRoute
  '/guides/integrations/$slug': typeof GuidesIntegrationsSlugRoute
  '/$teamId/heartbeats/new': typeof dashboardTeamIdHeartbeatsNewRoute
  '/$teamId/incidents/$incidentId': typeof dashboardTeamIdIncidentsIncidentIdRoute
  '/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/$teamId/status-pages/new': typeof dashboardTeamIdStatusPagesNewRoute
  '/$teamId/heartbeats': typeof dashboardTeamIdHeartbeatsIndexRoute
  '/$teamId/incidents': typeof dashboardTeamIdIncidentsIndexRoute
  '/$teamId/integrations': typeof dashboardTeamIdIntegrationsIndexRoute
  '/$teamId/monitors': typeof dashboardTeamIdMonitorsIndexRoute
  '/$teamId/status-pages': typeof dashboardTeamIdStatusPagesIndexRoute
  '/$teamId/heartbeats/$heartbeatId/edit': typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  '/$teamId/monitors/$monitorId/edit': typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  '/$teamId/monitors/$monitorId/maintenance': typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  '/$teamId/status-pages/$pageId/edit': typeof dashboardTeamIdStatusPagesPageIdEditRoute
  '/$teamId/heartbeats/$heartbeatId': typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  '/$teamId/monitors/$monitorId': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
  '/$teamId/status-pages/$pageId': typeof dashboardTeamIdStatusPagesPageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/status/$slug': typeof StatusSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/compare/': typeof CompareIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/(dashboard)/$teamId/new-team': typeof dashboardTeamIdNewTeamRoute
  '/(dashboard)/$teamId/settings': typeof dashboardTeamIdSettingsRoute
  '/(dashboard)/$teamId/support': typeof dashboardTeamIdSupportRoute
  '/(dashboard)/$teamId/team': typeof dashboardTeamIdTeamRoute
  '/guides/integrations/$slug': typeof GuidesIntegrationsSlugRoute
  '/(dashboard)/$teamId/heartbeats/new': typeof dashboardTeamIdHeartbeatsNewRoute
  '/(dashboard)/$teamId/incidents/$incidentId': typeof dashboardTeamIdIncidentsIncidentIdRoute
  '/(dashboard)/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/(dashboard)/$teamId/status-pages/new': typeof dashboardTeamIdStatusPagesNewRoute
  '/(dashboard)/$teamId/heartbeats/': typeof dashboardTeamIdHeartbeatsIndexRoute
  '/(dashboard)/$teamId/incidents/': typeof dashboardTeamIdIncidentsIndexRoute
  '/(dashboard)/$teamId/integrations/': typeof dashboardTeamIdIntegrationsIndexRoute
  '/(dashboard)/$teamId/monitors/': typeof dashboardTeamIdMonitorsIndexRoute
  '/(dashboard)/$teamId/status-pages/': typeof dashboardTeamIdStatusPagesIndexRoute
  '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit': typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  '/(dashboard)/$teamId/monitors/$monitorId/edit': typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  '/(dashboard)/$teamId/monitors/$monitorId/maintenance': typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  '/(dashboard)/$teamId/status-pages/$pageId/edit': typeof dashboardTeamIdStatusPagesPageIdEditRoute
  '/(dashboard)/$teamId/heartbeats/$heartbeatId/': typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  '/(dashboard)/$teamId/monitors/$monitorId/': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
  '/(dashboard)/$teamId/status-pages/$pageId/': typeof dashboardTeamIdStatusPagesPageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$teamId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/status/$slug'
    | '/use-cases/$slug'
    | '/compare'
    | '/guides'
    | '/use-cases'
    | '/$teamId/new-team'
    | '/$teamId/settings'
    | '/$teamId/support'
    | '/$teamId/team'
    | '/guides/integrations/$slug'
    | '/$teamId/heartbeats/new'
    | '/$teamId/incidents/$incidentId'
    | '/$teamId/monitors/new'
    | '/$teamId/status-pages/new'
    | '/$teamId/heartbeats'
    | '/$teamId/incidents'
    | '/$teamId/integrations'
    | '/$teamId/monitors'
    | '/$teamId/status-pages'
    | '/$teamId/heartbeats/$heartbeatId/edit'
    | '/$teamId/monitors/$monitorId/edit'
    | '/$teamId/monitors/$monitorId/maintenance'
    | '/$teamId/status-pages/$pageId/edit'
    | '/$teamId/heartbeats/$heartbeatId'
    | '/$teamId/monitors/$monitorId'
    | '/$teamId/status-pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$teamId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/status/$slug'
    | '/use-cases/$slug'
    | '/compare'
    | '/guides'
    | '/use-cases'
    | '/$teamId/new-team'
    | '/$teamId/settings'
    | '/$teamId/support'
    | '/$teamId/team'
    | '/guides/integrations/$slug'
    | '/$teamId/heartbeats/new'
    | '/$teamId/incidents/$incidentId'
    | '/$teamId/monitors/new'
    | '/$teamId/status-pages/new'
    | '/$teamId/heartbeats'
    | '/$teamId/incidents'
    | '/$teamId/integrations'
    | '/$teamId/monitors'
    | '/$teamId/status-pages'
    | '/$teamId/heartbeats/$heartbeatId/edit'
    | '/$teamId/monitors/$monitorId/edit'
    | '/$teamId/monitors/$monitorId/maintenance'
    | '/$teamId/status-pages/$pageId/edit'
    | '/$teamId/heartbeats/$heartbeatId'
    | '/$teamId/monitors/$monitorId'
    | '/$teamId/status-pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/$teamId'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/compare/$slug'
    | '/guides/$slug'
    | '/status/$slug'
    | '/use-cases/$slug'
    | '/compare/'
    | '/guides/'
    | '/use-cases/'
    | '/(dashboard)/$teamId/new-team'
    | '/(dashboard)/$teamId/settings'
    | '/(dashboard)/$teamId/support'
    | '/(dashboard)/$teamId/team'
    | '/guides/integrations/$slug'
    | '/(dashboard)/$teamId/heartbeats/new'
    | '/(dashboard)/$teamId/incidents/$incidentId'
    | '/(dashboard)/$teamId/monitors/new'
    | '/(dashboard)/$teamId/status-pages/new'
    | '/(dashboard)/$teamId/heartbeats/'
    | '/(dashboard)/$teamId/incidents/'
    | '/(dashboard)/$teamId/integrations/'
    | '/(dashboard)/$teamId/monitors/'
    | '/(dashboard)/$teamId/status-pages/'
    | '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit'
    | '/(dashboard)/$teamId/monitors/$monitorId/edit'
    | '/(dashboard)/$teamId/monitors/$monitorId/maintenance'
    | '/(dashboard)/$teamId/status-pages/$pageId/edit'
    | '/(dashboard)/$teamId/heartbeats/$heartbeatId/'
    | '/(dashboard)/$teamId/monitors/$monitorId/'
    | '/(dashboard)/$teamId/status-pages/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardTeamIdRouteRoute: typeof dashboardTeamIdRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  CompareSlugRoute: typeof CompareSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  StatusSlugRoute: typeof StatusSlugRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  CompareIndexRoute: typeof CompareIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
  GuidesIntegrationsSlugRoute: typeof GuidesIntegrationsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/$teamId': {
      id: '/(dashboard)/$teamId'
      path: '/$teamId'
      fullPath: '/$teamId'
      preLoaderRoute: typeof dashboardTeamIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/integrations/$slug': {
      id: '/guides/integrations/$slug'
      path: '/guides/integrations/$slug'
      fullPath: '/guides/integrations/$slug'
      preLoaderRoute: typeof GuidesIntegrationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/$teamId/team': {
      id: '/(dashboard)/$teamId/team'
      path: '/team'
      fullPath: '/$teamId/team'
      preLoaderRoute: typeof dashboardTeamIdTeamRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/support': {
      id: '/(dashboard)/$teamId/support'
      path: '/support'
      fullPath: '/$teamId/support'
      preLoaderRoute: typeof dashboardTeamIdSupportRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/settings': {
      id: '/(dashboard)/$teamId/settings'
      path: '/settings'
      fullPath: '/$teamId/settings'
      preLoaderRoute: typeof dashboardTeamIdSettingsRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/new-team': {
      id: '/(dashboard)/$teamId/new-team'
      path: '/new-team'
      fullPath: '/$teamId/new-team'
      preLoaderRoute: typeof dashboardTeamIdNewTeamRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/status-pages/': {
      id: '/(dashboard)/$teamId/status-pages/'
      path: '/status-pages'
      fullPath: '/$teamId/status-pages'
      preLoaderRoute: typeof dashboardTeamIdStatusPagesIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/': {
      id: '/(dashboard)/$teamId/monitors/'
      path: '/monitors'
      fullPath: '/$teamId/monitors'
      preLoaderRoute: typeof dashboardTeamIdMonitorsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/integrations/': {
      id: '/(dashboard)/$teamId/integrations/'
      path: '/integrations'
      fullPath: '/$teamId/integrations'
      preLoaderRoute: typeof dashboardTeamIdIntegrationsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/incidents/': {
      id: '/(dashboard)/$teamId/incidents/'
      path: '/incidents'
      fullPath: '/$teamId/incidents'
      preLoaderRoute: typeof dashboardTeamIdIncidentsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/': {
      id: '/(dashboard)/$teamId/heartbeats/'
      path: '/heartbeats'
      fullPath: '/$teamId/heartbeats'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/status-pages/new': {
      id: '/(dashboard)/$teamId/status-pages/new'
      path: '/status-pages/new'
      fullPath: '/$teamId/status-pages/new'
      preLoaderRoute: typeof dashboardTeamIdStatusPagesNewRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/new': {
      id: '/(dashboard)/$teamId/monitors/new'
      path: '/monitors/new'
      fullPath: '/$teamId/monitors/new'
      preLoaderRoute: typeof dashboardTeamIdMonitorsNewRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/incidents/$incidentId': {
      id: '/(dashboard)/$teamId/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/$teamId/incidents/$incidentId'
      preLoaderRoute: typeof dashboardTeamIdIncidentsIncidentIdRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/new': {
      id: '/(dashboard)/$teamId/heartbeats/new'
      path: '/heartbeats/new'
      fullPath: '/$teamId/heartbeats/new'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsNewRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/status-pages/$pageId/': {
      id: '/(dashboard)/$teamId/status-pages/$pageId/'
      path: '/status-pages/$pageId'
      fullPath: '/$teamId/status-pages/$pageId'
      preLoaderRoute: typeof dashboardTeamIdStatusPagesPageIdIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/$monitorId/': {
      id: '/(dashboard)/$teamId/monitors/$monitorId/'
      path: '/monitors/$monitorId'
      fullPath: '/$teamId/monitors/$monitorId'
      preLoaderRoute: typeof dashboardTeamIdMonitorsMonitorIdIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/$heartbeatId/': {
      id: '/(dashboard)/$teamId/heartbeats/$heartbeatId/'
      path: '/heartbeats/$heartbeatId'
      fullPath: '/$teamId/heartbeats/$heartbeatId'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/status-pages/$pageId/edit': {
      id: '/(dashboard)/$teamId/status-pages/$pageId/edit'
      path: '/status-pages/$pageId/edit'
      fullPath: '/$teamId/status-pages/$pageId/edit'
      preLoaderRoute: typeof dashboardTeamIdStatusPagesPageIdEditRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/$monitorId/maintenance': {
      id: '/(dashboard)/$teamId/monitors/$monitorId/maintenance'
      path: '/monitors/$monitorId/maintenance'
      fullPath: '/$teamId/monitors/$monitorId/maintenance'
      preLoaderRoute: typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/$monitorId/edit': {
      id: '/(dashboard)/$teamId/monitors/$monitorId/edit'
      path: '/monitors/$monitorId/edit'
      fullPath: '/$teamId/monitors/$monitorId/edit'
      preLoaderRoute: typeof dashboardTeamIdMonitorsMonitorIdEditRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit': {
      id: '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit'
      path: '/heartbeats/$heartbeatId/edit'
      fullPath: '/$teamId/heartbeats/$heartbeatId/edit'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
  }
}

interface dashboardTeamIdRouteRouteChildren {
  dashboardTeamIdNewTeamRoute: typeof dashboardTeamIdNewTeamRoute
  dashboardTeamIdSettingsRoute: typeof dashboardTeamIdSettingsRoute
  dashboardTeamIdSupportRoute: typeof dashboardTeamIdSupportRoute
  dashboardTeamIdTeamRoute: typeof dashboardTeamIdTeamRoute
  dashboardTeamIdHeartbeatsNewRoute: typeof dashboardTeamIdHeartbeatsNewRoute
  dashboardTeamIdIncidentsIncidentIdRoute: typeof dashboardTeamIdIncidentsIncidentIdRoute
  dashboardTeamIdMonitorsNewRoute: typeof dashboardTeamIdMonitorsNewRoute
  dashboardTeamIdStatusPagesNewRoute: typeof dashboardTeamIdStatusPagesNewRoute
  dashboardTeamIdHeartbeatsIndexRoute: typeof dashboardTeamIdHeartbeatsIndexRoute
  dashboardTeamIdIncidentsIndexRoute: typeof dashboardTeamIdIncidentsIndexRoute
  dashboardTeamIdIntegrationsIndexRoute: typeof dashboardTeamIdIntegrationsIndexRoute
  dashboardTeamIdMonitorsIndexRoute: typeof dashboardTeamIdMonitorsIndexRoute
  dashboardTeamIdStatusPagesIndexRoute: typeof dashboardTeamIdStatusPagesIndexRoute
  dashboardTeamIdHeartbeatsHeartbeatIdEditRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  dashboardTeamIdMonitorsMonitorIdEditRoute: typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  dashboardTeamIdMonitorsMonitorIdMaintenanceRoute: typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  dashboardTeamIdStatusPagesPageIdEditRoute: typeof dashboardTeamIdStatusPagesPageIdEditRoute
  dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  dashboardTeamIdMonitorsMonitorIdIndexRoute: typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
  dashboardTeamIdStatusPagesPageIdIndexRoute: typeof dashboardTeamIdStatusPagesPageIdIndexRoute
}

const dashboardTeamIdRouteRouteChildren: dashboardTeamIdRouteRouteChildren = {
  dashboardTeamIdNewTeamRoute: dashboardTeamIdNewTeamRoute,
  dashboardTeamIdSettingsRoute: dashboardTeamIdSettingsRoute,
  dashboardTeamIdSupportRoute: dashboardTeamIdSupportRoute,
  dashboardTeamIdTeamRoute: dashboardTeamIdTeamRoute,
  dashboardTeamIdHeartbeatsNewRoute: dashboardTeamIdHeartbeatsNewRoute,
  dashboardTeamIdIncidentsIncidentIdRoute:
    dashboardTeamIdIncidentsIncidentIdRoute,
  dashboardTeamIdMonitorsNewRoute: dashboardTeamIdMonitorsNewRoute,
  dashboardTeamIdStatusPagesNewRoute: dashboardTeamIdStatusPagesNewRoute,
  dashboardTeamIdHeartbeatsIndexRoute: dashboardTeamIdHeartbeatsIndexRoute,
  dashboardTeamIdIncidentsIndexRoute: dashboardTeamIdIncidentsIndexRoute,
  dashboardTeamIdIntegrationsIndexRoute: dashboardTeamIdIntegrationsIndexRoute,
  dashboardTeamIdMonitorsIndexRoute: dashboardTeamIdMonitorsIndexRoute,
  dashboardTeamIdStatusPagesIndexRoute: dashboardTeamIdStatusPagesIndexRoute,
  dashboardTeamIdHeartbeatsHeartbeatIdEditRoute:
    dashboardTeamIdHeartbeatsHeartbeatIdEditRoute,
  dashboardTeamIdMonitorsMonitorIdEditRoute:
    dashboardTeamIdMonitorsMonitorIdEditRoute,
  dashboardTeamIdMonitorsMonitorIdMaintenanceRoute:
    dashboardTeamIdMonitorsMonitorIdMaintenanceRoute,
  dashboardTeamIdStatusPagesPageIdEditRoute:
    dashboardTeamIdStatusPagesPageIdEditRoute,
  dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute:
    dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute,
  dashboardTeamIdMonitorsMonitorIdIndexRoute:
    dashboardTeamIdMonitorsMonitorIdIndexRoute,
  dashboardTeamIdStatusPagesPageIdIndexRoute:
    dashboardTeamIdStatusPagesPageIdIndexRoute,
}

const dashboardTeamIdRouteRouteWithChildren =
  dashboardTeamIdRouteRoute._addFileChildren(dashboardTeamIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardTeamIdRouteRoute: dashboardTeamIdRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  CompareSlugRoute: CompareSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  StatusSlugRoute: StatusSlugRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  CompareIndexRoute: CompareIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
  GuidesIntegrationsSlugRoute: GuidesIntegrationsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
