/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as dashboardTeamIdRouteRouteImport } from './routes/(dashboard)/$teamId/route'
import { Route as dashboardTeamIdSettingsRouteImport } from './routes/(dashboard)/$teamId/settings'
import { Route as dashboardTeamIdNotificationsIndexRouteImport } from './routes/(dashboard)/$teamId/notifications/index'
import { Route as dashboardTeamIdMonitorsIndexRouteImport } from './routes/(dashboard)/$teamId/monitors/index'
import { Route as dashboardTeamIdLogsIndexRouteImport } from './routes/(dashboard)/$teamId/logs/index'
import { Route as dashboardTeamIdIncidentsIndexRouteImport } from './routes/(dashboard)/$teamId/incidents/index'
import { Route as dashboardTeamIdHeartbeatsIndexRouteImport } from './routes/(dashboard)/$teamId/heartbeats/index'
import { Route as dashboardTeamIdMonitorsNewRouteImport } from './routes/(dashboard)/$teamId/monitors/new'
import { Route as dashboardTeamIdIncidentsKanbanRouteImport } from './routes/(dashboard)/$teamId/incidents/kanban'
import { Route as dashboardTeamIdIncidentsIncidentIdRouteImport } from './routes/(dashboard)/$teamId/incidents/$incidentId'
import { Route as dashboardTeamIdHeartbeatsNewRouteImport } from './routes/(dashboard)/$teamId/heartbeats/new'
import { Route as dashboardTeamIdMonitorsMonitorIdIndexRouteImport } from './routes/(dashboard)/$teamId/monitors/$monitorId/index'
import { Route as dashboardTeamIdHeartbeatsHeartbeatIdIndexRouteImport } from './routes/(dashboard)/$teamId/heartbeats/$heartbeatId/index'
import { Route as dashboardTeamIdMonitorsMonitorIdMaintenanceRouteImport } from './routes/(dashboard)/$teamId/monitors/$monitorId/maintenance'
import { Route as dashboardTeamIdMonitorsMonitorIdEditRouteImport } from './routes/(dashboard)/$teamId/monitors/$monitorId/edit'
import { Route as dashboardTeamIdHeartbeatsHeartbeatIdEditRouteImport } from './routes/(dashboard)/$teamId/heartbeats/$heartbeatId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTeamIdRouteRoute = dashboardTeamIdRouteRouteImport.update({
  id: '/(dashboard)/$teamId',
  path: '/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTeamIdSettingsRoute = dashboardTeamIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardTeamIdRouteRoute,
} as any)
const dashboardTeamIdNotificationsIndexRoute =
  dashboardTeamIdNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsIndexRoute =
  dashboardTeamIdMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdLogsIndexRoute =
  dashboardTeamIdLogsIndexRouteImport.update({
    id: '/logs/',
    path: '/logs/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdIncidentsIndexRoute =
  dashboardTeamIdIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsIndexRoute =
  dashboardTeamIdHeartbeatsIndexRouteImport.update({
    id: '/heartbeats/',
    path: '/heartbeats/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsNewRoute =
  dashboardTeamIdMonitorsNewRouteImport.update({
    id: '/monitors/new',
    path: '/monitors/new',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdIncidentsKanbanRoute =
  dashboardTeamIdIncidentsKanbanRouteImport.update({
    id: '/incidents/kanban',
    path: '/incidents/kanban',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdIncidentsIncidentIdRoute =
  dashboardTeamIdIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsNewRoute =
  dashboardTeamIdHeartbeatsNewRouteImport.update({
    id: '/heartbeats/new',
    path: '/heartbeats/new',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsMonitorIdIndexRoute =
  dashboardTeamIdMonitorsMonitorIdIndexRouteImport.update({
    id: '/monitors/$monitorId/',
    path: '/monitors/$monitorId/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute =
  dashboardTeamIdHeartbeatsHeartbeatIdIndexRouteImport.update({
    id: '/heartbeats/$heartbeatId/',
    path: '/heartbeats/$heartbeatId/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsMonitorIdMaintenanceRoute =
  dashboardTeamIdMonitorsMonitorIdMaintenanceRouteImport.update({
    id: '/monitors/$monitorId/maintenance',
    path: '/monitors/$monitorId/maintenance',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsMonitorIdEditRoute =
  dashboardTeamIdMonitorsMonitorIdEditRouteImport.update({
    id: '/monitors/$monitorId/edit',
    path: '/monitors/$monitorId/edit',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdHeartbeatsHeartbeatIdEditRoute =
  dashboardTeamIdHeartbeatsHeartbeatIdEditRouteImport.update({
    id: '/heartbeats/$heartbeatId/edit',
    path: '/heartbeats/$heartbeatId/edit',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$teamId/settings': typeof dashboardTeamIdSettingsRoute
  '/$teamId/heartbeats/new': typeof dashboardTeamIdHeartbeatsNewRoute
  '/$teamId/incidents/$incidentId': typeof dashboardTeamIdIncidentsIncidentIdRoute
  '/$teamId/incidents/kanban': typeof dashboardTeamIdIncidentsKanbanRoute
  '/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/$teamId/heartbeats': typeof dashboardTeamIdHeartbeatsIndexRoute
  '/$teamId/incidents': typeof dashboardTeamIdIncidentsIndexRoute
  '/$teamId/logs': typeof dashboardTeamIdLogsIndexRoute
  '/$teamId/monitors': typeof dashboardTeamIdMonitorsIndexRoute
  '/$teamId/notifications': typeof dashboardTeamIdNotificationsIndexRoute
  '/$teamId/heartbeats/$heartbeatId/edit': typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  '/$teamId/monitors/$monitorId/edit': typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  '/$teamId/monitors/$monitorId/maintenance': typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  '/$teamId/heartbeats/$heartbeatId': typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  '/$teamId/monitors/$monitorId': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$teamId/settings': typeof dashboardTeamIdSettingsRoute
  '/$teamId/heartbeats/new': typeof dashboardTeamIdHeartbeatsNewRoute
  '/$teamId/incidents/$incidentId': typeof dashboardTeamIdIncidentsIncidentIdRoute
  '/$teamId/incidents/kanban': typeof dashboardTeamIdIncidentsKanbanRoute
  '/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/$teamId/heartbeats': typeof dashboardTeamIdHeartbeatsIndexRoute
  '/$teamId/incidents': typeof dashboardTeamIdIncidentsIndexRoute
  '/$teamId/logs': typeof dashboardTeamIdLogsIndexRoute
  '/$teamId/monitors': typeof dashboardTeamIdMonitorsIndexRoute
  '/$teamId/notifications': typeof dashboardTeamIdNotificationsIndexRoute
  '/$teamId/heartbeats/$heartbeatId/edit': typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  '/$teamId/monitors/$monitorId/edit': typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  '/$teamId/monitors/$monitorId/maintenance': typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  '/$teamId/heartbeats/$heartbeatId': typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  '/$teamId/monitors/$monitorId': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(dashboard)/$teamId/settings': typeof dashboardTeamIdSettingsRoute
  '/(dashboard)/$teamId/heartbeats/new': typeof dashboardTeamIdHeartbeatsNewRoute
  '/(dashboard)/$teamId/incidents/$incidentId': typeof dashboardTeamIdIncidentsIncidentIdRoute
  '/(dashboard)/$teamId/incidents/kanban': typeof dashboardTeamIdIncidentsKanbanRoute
  '/(dashboard)/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/(dashboard)/$teamId/heartbeats/': typeof dashboardTeamIdHeartbeatsIndexRoute
  '/(dashboard)/$teamId/incidents/': typeof dashboardTeamIdIncidentsIndexRoute
  '/(dashboard)/$teamId/logs/': typeof dashboardTeamIdLogsIndexRoute
  '/(dashboard)/$teamId/monitors/': typeof dashboardTeamIdMonitorsIndexRoute
  '/(dashboard)/$teamId/notifications/': typeof dashboardTeamIdNotificationsIndexRoute
  '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit': typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  '/(dashboard)/$teamId/monitors/$monitorId/edit': typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  '/(dashboard)/$teamId/monitors/$monitorId/maintenance': typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  '/(dashboard)/$teamId/heartbeats/$heartbeatId/': typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  '/(dashboard)/$teamId/monitors/$monitorId/': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$teamId'
    | '/login'
    | '/signup'
    | '/$teamId/settings'
    | '/$teamId/heartbeats/new'
    | '/$teamId/incidents/$incidentId'
    | '/$teamId/incidents/kanban'
    | '/$teamId/monitors/new'
    | '/$teamId/heartbeats'
    | '/$teamId/incidents'
    | '/$teamId/logs'
    | '/$teamId/monitors'
    | '/$teamId/notifications'
    | '/$teamId/heartbeats/$heartbeatId/edit'
    | '/$teamId/monitors/$monitorId/edit'
    | '/$teamId/monitors/$monitorId/maintenance'
    | '/$teamId/heartbeats/$heartbeatId'
    | '/$teamId/monitors/$monitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$teamId'
    | '/login'
    | '/signup'
    | '/$teamId/settings'
    | '/$teamId/heartbeats/new'
    | '/$teamId/incidents/$incidentId'
    | '/$teamId/incidents/kanban'
    | '/$teamId/monitors/new'
    | '/$teamId/heartbeats'
    | '/$teamId/incidents'
    | '/$teamId/logs'
    | '/$teamId/monitors'
    | '/$teamId/notifications'
    | '/$teamId/heartbeats/$heartbeatId/edit'
    | '/$teamId/monitors/$monitorId/edit'
    | '/$teamId/monitors/$monitorId/maintenance'
    | '/$teamId/heartbeats/$heartbeatId'
    | '/$teamId/monitors/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/$teamId'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(dashboard)/$teamId/settings'
    | '/(dashboard)/$teamId/heartbeats/new'
    | '/(dashboard)/$teamId/incidents/$incidentId'
    | '/(dashboard)/$teamId/incidents/kanban'
    | '/(dashboard)/$teamId/monitors/new'
    | '/(dashboard)/$teamId/heartbeats/'
    | '/(dashboard)/$teamId/incidents/'
    | '/(dashboard)/$teamId/logs/'
    | '/(dashboard)/$teamId/monitors/'
    | '/(dashboard)/$teamId/notifications/'
    | '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit'
    | '/(dashboard)/$teamId/monitors/$monitorId/edit'
    | '/(dashboard)/$teamId/monitors/$monitorId/maintenance'
    | '/(dashboard)/$teamId/heartbeats/$heartbeatId/'
    | '/(dashboard)/$teamId/monitors/$monitorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardTeamIdRouteRoute: typeof dashboardTeamIdRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/$teamId': {
      id: '/(dashboard)/$teamId'
      path: '/$teamId'
      fullPath: '/$teamId'
      preLoaderRoute: typeof dashboardTeamIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/$teamId/settings': {
      id: '/(dashboard)/$teamId/settings'
      path: '/settings'
      fullPath: '/$teamId/settings'
      preLoaderRoute: typeof dashboardTeamIdSettingsRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/notifications/': {
      id: '/(dashboard)/$teamId/notifications/'
      path: '/notifications'
      fullPath: '/$teamId/notifications'
      preLoaderRoute: typeof dashboardTeamIdNotificationsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/': {
      id: '/(dashboard)/$teamId/monitors/'
      path: '/monitors'
      fullPath: '/$teamId/monitors'
      preLoaderRoute: typeof dashboardTeamIdMonitorsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/logs/': {
      id: '/(dashboard)/$teamId/logs/'
      path: '/logs'
      fullPath: '/$teamId/logs'
      preLoaderRoute: typeof dashboardTeamIdLogsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/incidents/': {
      id: '/(dashboard)/$teamId/incidents/'
      path: '/incidents'
      fullPath: '/$teamId/incidents'
      preLoaderRoute: typeof dashboardTeamIdIncidentsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/': {
      id: '/(dashboard)/$teamId/heartbeats/'
      path: '/heartbeats'
      fullPath: '/$teamId/heartbeats'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/new': {
      id: '/(dashboard)/$teamId/monitors/new'
      path: '/monitors/new'
      fullPath: '/$teamId/monitors/new'
      preLoaderRoute: typeof dashboardTeamIdMonitorsNewRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/incidents/kanban': {
      id: '/(dashboard)/$teamId/incidents/kanban'
      path: '/incidents/kanban'
      fullPath: '/$teamId/incidents/kanban'
      preLoaderRoute: typeof dashboardTeamIdIncidentsKanbanRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/incidents/$incidentId': {
      id: '/(dashboard)/$teamId/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/$teamId/incidents/$incidentId'
      preLoaderRoute: typeof dashboardTeamIdIncidentsIncidentIdRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/new': {
      id: '/(dashboard)/$teamId/heartbeats/new'
      path: '/heartbeats/new'
      fullPath: '/$teamId/heartbeats/new'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsNewRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/$monitorId/': {
      id: '/(dashboard)/$teamId/monitors/$monitorId/'
      path: '/monitors/$monitorId'
      fullPath: '/$teamId/monitors/$monitorId'
      preLoaderRoute: typeof dashboardTeamIdMonitorsMonitorIdIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/$heartbeatId/': {
      id: '/(dashboard)/$teamId/heartbeats/$heartbeatId/'
      path: '/heartbeats/$heartbeatId'
      fullPath: '/$teamId/heartbeats/$heartbeatId'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/$monitorId/maintenance': {
      id: '/(dashboard)/$teamId/monitors/$monitorId/maintenance'
      path: '/monitors/$monitorId/maintenance'
      fullPath: '/$teamId/monitors/$monitorId/maintenance'
      preLoaderRoute: typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/$monitorId/edit': {
      id: '/(dashboard)/$teamId/monitors/$monitorId/edit'
      path: '/monitors/$monitorId/edit'
      fullPath: '/$teamId/monitors/$monitorId/edit'
      preLoaderRoute: typeof dashboardTeamIdMonitorsMonitorIdEditRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit': {
      id: '/(dashboard)/$teamId/heartbeats/$heartbeatId/edit'
      path: '/heartbeats/$heartbeatId/edit'
      fullPath: '/$teamId/heartbeats/$heartbeatId/edit'
      preLoaderRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
  }
}

interface dashboardTeamIdRouteRouteChildren {
  dashboardTeamIdSettingsRoute: typeof dashboardTeamIdSettingsRoute
  dashboardTeamIdHeartbeatsNewRoute: typeof dashboardTeamIdHeartbeatsNewRoute
  dashboardTeamIdIncidentsIncidentIdRoute: typeof dashboardTeamIdIncidentsIncidentIdRoute
  dashboardTeamIdIncidentsKanbanRoute: typeof dashboardTeamIdIncidentsKanbanRoute
  dashboardTeamIdMonitorsNewRoute: typeof dashboardTeamIdMonitorsNewRoute
  dashboardTeamIdHeartbeatsIndexRoute: typeof dashboardTeamIdHeartbeatsIndexRoute
  dashboardTeamIdIncidentsIndexRoute: typeof dashboardTeamIdIncidentsIndexRoute
  dashboardTeamIdLogsIndexRoute: typeof dashboardTeamIdLogsIndexRoute
  dashboardTeamIdMonitorsIndexRoute: typeof dashboardTeamIdMonitorsIndexRoute
  dashboardTeamIdNotificationsIndexRoute: typeof dashboardTeamIdNotificationsIndexRoute
  dashboardTeamIdHeartbeatsHeartbeatIdEditRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdEditRoute
  dashboardTeamIdMonitorsMonitorIdEditRoute: typeof dashboardTeamIdMonitorsMonitorIdEditRoute
  dashboardTeamIdMonitorsMonitorIdMaintenanceRoute: typeof dashboardTeamIdMonitorsMonitorIdMaintenanceRoute
  dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute: typeof dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute
  dashboardTeamIdMonitorsMonitorIdIndexRoute: typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}

const dashboardTeamIdRouteRouteChildren: dashboardTeamIdRouteRouteChildren = {
  dashboardTeamIdSettingsRoute: dashboardTeamIdSettingsRoute,
  dashboardTeamIdHeartbeatsNewRoute: dashboardTeamIdHeartbeatsNewRoute,
  dashboardTeamIdIncidentsIncidentIdRoute:
    dashboardTeamIdIncidentsIncidentIdRoute,
  dashboardTeamIdIncidentsKanbanRoute: dashboardTeamIdIncidentsKanbanRoute,
  dashboardTeamIdMonitorsNewRoute: dashboardTeamIdMonitorsNewRoute,
  dashboardTeamIdHeartbeatsIndexRoute: dashboardTeamIdHeartbeatsIndexRoute,
  dashboardTeamIdIncidentsIndexRoute: dashboardTeamIdIncidentsIndexRoute,
  dashboardTeamIdLogsIndexRoute: dashboardTeamIdLogsIndexRoute,
  dashboardTeamIdMonitorsIndexRoute: dashboardTeamIdMonitorsIndexRoute,
  dashboardTeamIdNotificationsIndexRoute:
    dashboardTeamIdNotificationsIndexRoute,
  dashboardTeamIdHeartbeatsHeartbeatIdEditRoute:
    dashboardTeamIdHeartbeatsHeartbeatIdEditRoute,
  dashboardTeamIdMonitorsMonitorIdEditRoute:
    dashboardTeamIdMonitorsMonitorIdEditRoute,
  dashboardTeamIdMonitorsMonitorIdMaintenanceRoute:
    dashboardTeamIdMonitorsMonitorIdMaintenanceRoute,
  dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute:
    dashboardTeamIdHeartbeatsHeartbeatIdIndexRoute,
  dashboardTeamIdMonitorsMonitorIdIndexRoute:
    dashboardTeamIdMonitorsMonitorIdIndexRoute,
}

const dashboardTeamIdRouteRouteWithChildren =
  dashboardTeamIdRouteRoute._addFileChildren(dashboardTeamIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardTeamIdRouteRoute: dashboardTeamIdRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
