import { type Location } from "./schemas";

export const LOCATIONS: { id: Location; label: string }[] = [
  { id: "wnam", label: "Western North America" },
  { id: "enam", label: "Eastern North America" },
  { id: "sam", label: "South America" },
  { id: "weur", label: "Western Europe" },
  { id: "eeur", label: "Eastern Europe" },
  { id: "apac", label: "Asia Pacific" },
  { id: "oc", label: "Oceania" },
  { id: "afr", label: "Africa" },
  { id: "me", label: "Middle East" },
];

export const HTTP_METHODS = [
  "get",
  "post",
  "head",
  "put",
  "patch",
  "delete",
  "options",
] as const;

export type HttpMethod = (typeof HTTP_METHODS)[number];

export const INTERVALS = [
  { value: 60000, label: "1 minute" },
  { value: 300000, label: "5 minutes" },
  { value: 600000, label: "10 minutes" },
  { value: 900000, label: "15 minutes" },
  { value: 1800000, label: "30 minutes" },
];

export const HTTP_STATUS_CODES: Record<number, string> = {
  100: "Continue",
  101: "Switching Protocols",
  102: "Processing",
  103: "Early Hints",
  200: "OK",
  201: "Created",
  202: "Accepted",
  203: "Non-Authoritative Information",
  204: "No Content",
  205: "Reset Content",
  206: "Partial Content",
  207: "Multi-Status",
  208: "Already Reported",
  226: "IM Used",
  300: "Multiple Choices",
  301: "Moved Permanently",
  302: "Found",
  303: "See Other",
  304: "Not Modified",
  305: "Use Proxy",
  307: "Temporary Redirect",
  308: "Permanent Redirect",
  400: "Bad Request",
  401: "Unauthorized",
  402: "Payment Required",
  403: "Forbidden",
  404: "Not Found",
  405: "Method Not Allowed",
  406: "Not Acceptable",
  407: "Proxy Authentication Required",
  408: "Request Timeout",
  409: "Conflict",
  410: "Gone",
  411: "Length Required",
  412: "Precondition Failed",
  413: "Payload Too Large",
  414: "URI Too Long",
  415: "Unsupported Media Type",
  416: "Range Not Satisfiable",
  417: "Expectation Failed",
  418: "I'm a teapot",
  421: "Misdirected Request",
  422: "Unprocessable Entity",
  423: "Locked",
  424: "Failed Dependency",
  425: "Too Early",
  426: "Upgrade Required",
  428: "Precondition Required",
  429: "Too Many Requests",
  431: "Request Header Fields Too Large",
  451: "Unavailable For Legal Reasons",
  500: "Internal Server Error",
  501: "Not Implemented",
  502: "Bad Gateway",
  503: "Service Unavailable",
  504: "Gateway Timeout",
  505: "HTTP Version Not Supported",
  506: "Variant Also Negotiates",
  507: "Insufficient Storage",
  508: "Loop Detected",
  510: "Not Extended",
  511: "Network Authentication Required",
};

export const STATUS_CODE_OPTIONS = [
  {
    type: "range" as const,
    value: "1xx",
    label: "1xx (Informational)",
    codes: Array.from({ length: 100 }, (_, i) => 100 + i),
  },
  {
    type: "range" as const,
    value: "2xx",
    label: "2xx (Success)",
    codes: Array.from({ length: 100 }, (_, i) => 200 + i),
  },
  {
    type: "range" as const,
    value: "3xx",
    label: "3xx (Redirect)",
    codes: Array.from({ length: 100 }, (_, i) => 300 + i),
  },
  {
    type: "range" as const,
    value: "4xx",
    label: "4xx (Client Error)",
    codes: Array.from({ length: 100 }, (_, i) => 400 + i),
  },
  {
    type: "range" as const,
    value: "5xx",
    label: "5xx (Server Error)",
    codes: Array.from({ length: 100 }, (_, i) => 500 + i),
  },
  ...Object.entries(HTTP_STATUS_CODES).map(([code, label]) => ({
    type: "code" as const,
    value: code,
    label: `${code} ${label}`,
    codes: [parseInt(code, 10)],
  })),
];
