/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as dashboardTeamIdRouteRouteImport } from './routes/(dashboard)/$teamId/route'
import { Route as dashboardTeamIdMonitorsIndexRouteImport } from './routes/(dashboard)/$teamId/monitors/index'
import { Route as dashboardTeamIdMonitorsNewRouteImport } from './routes/(dashboard)/$teamId/monitors/new'
import { Route as dashboardTeamIdMonitorsMonitorIdIndexRouteImport } from './routes/(dashboard)/$teamId/monitors/$monitorId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTeamIdRouteRoute = dashboardTeamIdRouteRouteImport.update({
  id: '/(dashboard)/$teamId',
  path: '/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTeamIdMonitorsIndexRoute =
  dashboardTeamIdMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsNewRoute =
  dashboardTeamIdMonitorsNewRouteImport.update({
    id: '/monitors/new',
    path: '/monitors/new',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)
const dashboardTeamIdMonitorsMonitorIdIndexRoute =
  dashboardTeamIdMonitorsMonitorIdIndexRouteImport.update({
    id: '/monitors/$monitorId/',
    path: '/monitors/$monitorId/',
    getParentRoute: () => dashboardTeamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/$teamId/monitors': typeof dashboardTeamIdMonitorsIndexRoute
  '/$teamId/monitors/$monitorId': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/$teamId/monitors': typeof dashboardTeamIdMonitorsIndexRoute
  '/$teamId/monitors/$monitorId': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)/$teamId': typeof dashboardTeamIdRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(dashboard)/$teamId/monitors/new': typeof dashboardTeamIdMonitorsNewRoute
  '/(dashboard)/$teamId/monitors/': typeof dashboardTeamIdMonitorsIndexRoute
  '/(dashboard)/$teamId/monitors/$monitorId/': typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$teamId'
    | '/login'
    | '/signup'
    | '/$teamId/monitors/new'
    | '/$teamId/monitors'
    | '/$teamId/monitors/$monitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$teamId'
    | '/login'
    | '/signup'
    | '/$teamId/monitors/new'
    | '/$teamId/monitors'
    | '/$teamId/monitors/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/$teamId'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(dashboard)/$teamId/monitors/new'
    | '/(dashboard)/$teamId/monitors/'
    | '/(dashboard)/$teamId/monitors/$monitorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardTeamIdRouteRoute: typeof dashboardTeamIdRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/$teamId': {
      id: '/(dashboard)/$teamId'
      path: '/$teamId'
      fullPath: '/$teamId'
      preLoaderRoute: typeof dashboardTeamIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/$teamId/monitors/': {
      id: '/(dashboard)/$teamId/monitors/'
      path: '/monitors'
      fullPath: '/$teamId/monitors'
      preLoaderRoute: typeof dashboardTeamIdMonitorsIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/new': {
      id: '/(dashboard)/$teamId/monitors/new'
      path: '/monitors/new'
      fullPath: '/$teamId/monitors/new'
      preLoaderRoute: typeof dashboardTeamIdMonitorsNewRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
    '/(dashboard)/$teamId/monitors/$monitorId/': {
      id: '/(dashboard)/$teamId/monitors/$monitorId/'
      path: '/monitors/$monitorId'
      fullPath: '/$teamId/monitors/$monitorId'
      preLoaderRoute: typeof dashboardTeamIdMonitorsMonitorIdIndexRouteImport
      parentRoute: typeof dashboardTeamIdRouteRoute
    }
  }
}

interface dashboardTeamIdRouteRouteChildren {
  dashboardTeamIdMonitorsNewRoute: typeof dashboardTeamIdMonitorsNewRoute
  dashboardTeamIdMonitorsIndexRoute: typeof dashboardTeamIdMonitorsIndexRoute
  dashboardTeamIdMonitorsMonitorIdIndexRoute: typeof dashboardTeamIdMonitorsMonitorIdIndexRoute
}

const dashboardTeamIdRouteRouteChildren: dashboardTeamIdRouteRouteChildren = {
  dashboardTeamIdMonitorsNewRoute: dashboardTeamIdMonitorsNewRoute,
  dashboardTeamIdMonitorsIndexRoute: dashboardTeamIdMonitorsIndexRoute,
  dashboardTeamIdMonitorsMonitorIdIndexRoute:
    dashboardTeamIdMonitorsMonitorIdIndexRoute,
}

const dashboardTeamIdRouteRouteWithChildren =
  dashboardTeamIdRouteRoute._addFileChildren(dashboardTeamIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardTeamIdRouteRoute: dashboardTeamIdRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
